name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-with-esp-idf:
    name: Build with ESP-IDF
    runs-on: ubuntu-latest
    container: espressif/idf:v5.0.2
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build
      - name: Save Workflow Context
        id: workflow_context
        env:
          ISSUE_NUMBER: ${{ github.event.number }}
          EVENT_NAME: ${{ github.event_name }}
          BUILD_RESULT: build_result-${{ github.sha }}
        run: |
          echo $BUILD_RESULT > ./build/build_result_artifacts
          echo $ISSUE_NUMBER > ./build/issue_number
          echo $EVENT_NAME > ./build/event_name
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.workflow_context.outputs.BUILD_RESULT }}
          path: build
