name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-on-esp-idf-v5_0_2:
    name: Build on ESP-IDF v5.0.2
    runs-on: ubuntu-latest
    container: espressif/idf:v5.0.2
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Prepare
        run: |
          apt-get update && apt-get -y install cppcheck
          git config --system --add safe.directory '*'
          echo "CODECHECKER_RESULT=$(echo .github/codechecker_result.txt)" >> \
            $GITHUB_ENV
          echo "CODECHECKER_BASE=$(echo .github/codechecker.baseline)" >> \
            $GITHUB_ENV
          echo "CODECHECKER_BASE_TMP=$(echo .github/tmp.baseline)" >> \
            $GITHUB_ENV
      - name: UnitTest
        run: |
          echo "Hello" || true
      - name: Build
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build
      - name: Static Analysis
        run: |
          $IDF_PATH/tools/idf_tools.py install xtensa-clang
          . $IDF_PATH/export.sh
          pip3 install codechecker
          sed -i 's/-fno-tree-switch-conversion//g' build/compile_commands.json
          sed -i 's/-fstrict-volatile-bitfields//g' build/compile_commands.json
          sed -i 's/-std=gnu17//g' build/compile_commands.json
          CodeChecker analyze ./build/compile_commands.json --enable sensitive \
            --output ./reports --ignore .codechecker.exclude
          git checkout main $CODECHECKER_BASE || true
          CodeChecker parse ./reports -e baseline -o $CODECHECKER_BASE_TMP || true
          CodeChecker cmd diff -b $CODECHECKER_BASE \
            -n ./reports --new > $CODECHECKER_RESULT ||
            CodeChecker parse reports > $CODECHECKER_RESULT
      - name: Process Analysis Result
        if: always()
        run: |
          sed -i '1s/^/```\n/' $CODECHECKER_RESULT
          echo "\n\`\`\`" >> $CODECHECKER_RESULT
          cp $CODECHECKER_BASE_TMP $CODECHECKER_BASE
      - name: Comment
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const filepath = "${{ env.CODECHECKER_RESULT }}";
            const body = fs.readFileSync(filepath, "utf-8");
            github.rest.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
      - name: Store codechecker baseline
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ env.CODECHECKER_BASE }}
          default_author: github_actions
          push: origin HEAD:${{ github.head_ref }} --force
